server:
  listenAddress: "localhost:8080"
  timeout: 2s
  paths:
    recordUpload: "/upload"

localStorage:
  rootPath: "/var"
  cleanInterval: 20m
  reservedCapacity: 2147483648 # 2.0 GB

services:
  default:
    notification:
      discord:
        webhookUrl: "https://discord.com/your_webhook"
    upload:
      googleDrive:
        timeout: 30m
        credentialPath: "./config/example-credential.json"
        reservedCapacity: 1610612736 # 1.5 GB
        parentFolderId: "parent_folder_id"
  streamers:
    - roomId: 1001 # test room id
      notification:
        discord:
          webhookUrl: "https://discord.com/your_webhook"
      upload:
        googleDrive:
          timeout: 30m
          credentialPath: "./config/example-credential.json"
          reservedCapacity: 1610612736 # 1.5 GB
          parentFolderId: "parent_folder_id"
