server:
  listenAddress: "localhost:8080"
  timeout: 2s
  paths:
    recordUpload: "/upload"

services:
  default:
    discord:
      webhookUrl: "https://discord.com/your_webhook"
    storage:
      rootPath: "/var"
      googleDrive:
        timeout: 30m
        credentialPath: "./config/example-credential.json"
        reservedCapacity: 1610612736 # 1.5 GB
        parentFolderId: "parent_folder_id"
  streamers:
    - roomId: 1001 # test room id
      discord:
        webhookUrl: "https://discord.com/your_webhook"
      storage:
        rootPath: "/var"
        googleDrive:
          timeout: 30m
          credentialPath: "./config/example-credential.json"
          reservedCapacity: 1610612736 # 1.5 GB
          parentFolderId: "parent_folder_id"
